# Generated by Django 4.0.3 on 2022-04-01 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='test_database1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('str_area1', models.CharField(max_length=10)),
                ('str_area2', models.CharField(max_length=100)),
                ('date_field', models.DateField()),
            ],
        ),
    ]
