# Generated by Django 4.0.3 on 2022-04-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='test_database2',
            fields=[
                ('idon', models.AutoField(primary_key=True, serialize=False)),
                ('str_areaon1', models.CharField(max_length=10)),
                ('str_areaon2', models.CharField(max_length=100)),
                ('date_fieldon', models.DateField()),
            ],
        ),
    ]
