# Generated by Django 4.0.3 on 2022-04-11 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('Syusai', models.CharField(max_length=5)),
                ('start_day', models.DateField()),
                ('end_day', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='test_database2',
            fields=[
                ('idon', models.AutoField(primary_key=True, serialize=False)),
                ('str_areaon1', models.CharField(max_length=10)),
                ('str_areaon2', models.CharField(max_length=100)),
                ('date_fieldon', models.DateField()),
            ],
        ),
    ]
