# Generated by Django 4.0.3 on 2022-04-11 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkApp', '0002_test_database2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('Syusai', models.CharField(max_length=5)),
                ('start_day', models.DateField()),
                ('end_day', models.DateField()),
            ],
        ),
    ]
